"""empty message

Revision ID: 0702f16dd063
Revises: e0569291befc
Create Date: 2020-10-01 13:15:43.129794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0702f16dd063'
down_revision = 'e0569291befc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('cards', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('lists', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('cards', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('boards', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
